export interface ITimeTrackerListResponse {
    id: number;
    owner: number;
    week: number;
    year: number;
    timetracker_id: number;
    created_by: number;
    created_at: string;
    updated_by: string;
    updated_at: string;
    custom_approver: number;
    date_range: string;
    toplam_saat: number;
    ay: number;
    month: number;
    custom_approver_2: number;
    calisan: number;
    tamamlanan_saat: string;
    tarih: string;
    tamamlandi: boolean;
    hafta_toplami: number;
    kalan: number;
    ilgili_ay: string;
    approver: number;
    process_date: string;
    approver_order: string;
    process_status_list: string;
    shared_users: string;
    shared_user_groups: string;
    shared_users_edit: string;
    shared_user_groups_edit;
}